name: CI
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, reopened, synchronize]
jobs:
  test:
    name: >
      Test
      on ${{ matrix.platform.os }}
      with ${{ matrix.rust.toolchain }}
      ${{ (matrix.rust.rust-flags && format(' and {0}', matrix.rust.rust-flags)) }}
    runs-on: ${{ matrix.platform.os }}
    strategy:
      fail-fast: false
      matrix:
        platform:
          - os: ubuntu-latest
            rust-target: x86_64-unknown-linux-gnu
          - os: macos-latest
            rust-target: aarch64-apple-darwin
        rust:
          - toolchain: stable
          - toolchain: nightly
          # Test with panic=unwind
          - toolchain: nightly
            rust-flags: "-Cpanic=unwind"
            unstable-flags: "-Zbuild-std"
          # Minimum supported Rust version (see Cargo.toml)
          - toolchain: 1.88.0
    steps:
      - name: Checkout sources
        uses: actions/checkout@v6

      - name: Install Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: ${{ matrix.rust.toolchain }}
          target: wasm32-unknown-unknown
          components: rust-src
          rustflags: ${{ matrix.rust.rust-flags }}

      - name: Install Node 24
        uses: actions/setup-node@v6
        with:
          node-version: 24

      - name: Run cargo check
        run: cargo check --target=wasm32-unknown-unknown ${{ matrix.rust.unstable-flags }}

      - name: Run cargo test
        run: cargo test --target=${{ matrix.platform.rust-target }}

      - name: Install wasm-pack
        run: curl https://wasm-bindgen.github.io/wasm-pack/installer/init.sh -sSf | bash

      - name: Test on Node
        run: wasm-pack test --node -- ${{ matrix.rust.unstable-flags }}

      - name: Test on Chrome
        run: wasm-pack test --headless --chrome -- ${{ matrix.rust.unstable-flags }}
        env:
          WASM_BINDGEN_USE_BROWSER: "1"

      - name: Test on Firefox
        run: wasm-pack test --headless --firefox -- ${{ matrix.rust.unstable-flags }}
        env:
          WASM_BINDGEN_USE_BROWSER: "1"

      - name: Test on Safari
        if: ${{ startsWith(matrix.platform.os, 'macos-') }}
        run: wasm-pack test --headless --safari -- ${{ matrix.rust.unstable-flags }}
        env:
          WASM_BINDGEN_USE_BROWSER: "1"
          WASM_BINDGEN_DRIVER_TIMEOUT: 10

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v6

      - name: Install stable Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
          target: wasm32-unknown-unknown
          components: rustfmt, clippy

      - name: Run cargo fmt
        run: cargo fmt --all -- --check

      - name: Run cargo clippy
        run: cargo clippy --target=wasm32-unknown-unknown
